openapi: "3.0.0"
info:
  version: "1.0.0"
  title: Service Icons

paths:
  /v{ver}/color/checker:
    get:
      summary: route to check if the service is up.
      operationId: checker
      tags:
        - checker
      parameters:
        - in: path
          name: ver
          schema:
            type: integer
          required: true
          description: Version number of the service
      responses:
        "200":
          description: Returning OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: Always true for 200 response
                  message:
                    type: string
                  version:
                    type: string
                    description: Application version string (SemVer 2.0)
                example:
                  success: true
                  message: "OK"
                  version: "v0.2.0-beta.1"
        "400":
          description: Bad Requests. Caused when unsupported versions of the service are called.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
                example:
                  success: false
                  error:
                    code: 400
                    message: "unsupported version of service"
        "500":
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
                example:
                  success: false
                  error:
                    code: 500
                    message: "An internal error occurred"

  /v{ver}/color/{r},{g},{b}/{filename}:
    get:
      summary: Colorized the specified symbol with the specified color.
      operationId: color
      tags:
        - color
      parameters:
        - in: path
          name: ver
          schema:
            type: integer
          required: true
          description: Version number of the service
        - in: path
          name: r
          schema:
            type: integer
          required: true
          description: The value of the red color channel
        - in: path
          name: g
          schema:
            type: integer
          required: true
          description: The value of the greeb color channel
        - in: path
          name: b
          schema:
            type: integer
          required: true
          description: The value of the blue color channel
        - in: path
          name: filename
          schema:
            type: string
          required: true
          description: Filename of the symbol to be colorized
      responses:
        "200":
          description: Returns the symbol colorized in the specified colors.
          content:
            image/png:
              schema:
                type: string
                format: binary

        "400":
          description: Bad Requests. This can be caused by ill defined parameters, or the host/the domain is/are not part of the authorised hosts/domains or the version is not supported.
          content:
            text/html:
              schema:
                type: string
                example: "Color channel values must be integers in the range of 0 to 255."

        "500":
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
                example:
                  success: false
                  error:
                    code: 500
                    message: "An internal error occurred"

components:
  schemas:
    error:
      type: object
      properties:
        success:
          type: boolean
          description: Always false in case of error.
        error:
          type: object
          properties:
            code:
              type: integer
              description: Error code.
            message:
              type: string
              description: Description of the error.
